### ISSUE TITLE
ResponseError: unknown command 'SCAN'

### ISSUE THREAD

**Issue by kiot389** [InQuest/omnibus#30]
I'm encountering an error when running most commands. Such as in the sample: omnibus>> new inquest.net
ResponseError: unknown command 'SCAN'
EXCEPTION of type 'ResponseError' occurred with message: 'unknown command 'SCAN''

**Comment by deadbits** [comment]
@kiot389 I'm really not sure what's going on on your side. Can you copy and paste your entire session output that causes this error with the full exception?

Looking through my source code there isn't even a variable or anything named "SCAN" that would be incorrectly referenced somewhere.

I just did a completely fresh install from the Master branch of this repo, ran `pip install --user -r -requirements.txt` then `python omnibus-cli.py` and following without any error like that at all.


```
Welcome to the Omnibus shell! Type "session" to get started or "help" to view all commands.
omnibus >> new deadbits.org
[~] Created new artifact (deadbits.org - host)
[~] Opened new session
Artifact ID: 1
omnibus >> new inquest.net
[~] Created new artifact (inquest.net - host)
Artifact ID: 2
omnibus >>
```
