### ISSUE TITLE
Recommend increasing required cmd2 version from 0.8.2 to 0.8.9

### ISSUE THREAD

**Issue by tleonhardt** [InQuest/omnibus#31]
I see that you have a requirement specifically on `cmd2` version 0.8.2 in your **requirements.txt** file.  I recommend that you increase it to version 0.8.9 in order to pick up numerous bugfixes while maintaining full compatibility with the previous version you were depending upon.

**Comment by deadbits** [comment]
Thanks for the heads up! I haven't kept up much with this project lately unfortunately (hence the 17 tickets I created for myself and are still open), but this is a quick fix :)

**Comment by deadbits** [comment]
Done and done!
Commit: https://github.com/InQuest/omnibus/commit/4e2c7159ebbd15beab1ab1480bb93e31588603f4
